### ISSUE TITLE
Can you describe  how to  run fletcher  on alveo? 

### ISSUE THREAD

**Issue by yaoye-ali** [abs-tudelft/fletcher-alveo#38]
can you supply  the run steps . Thank you !

**Comment by mbrobbel** [comment]
I suggest you start with the sum example [here](https://github.com/abs-tudelft/fletcher-alveo/tree/master/examples/sum). You can build the software using the CMake file [here](https://github.com/abs-tudelft/fletcher-alveo/blob/master/examples/sum/sw/CMakeLists.txt). You can build the hardware using the Makefiles [here](https://github.com/abs-tudelft/fletcher-alveo/blob/master/examples/sum/hw/Makefile) and [here](https://github.com/abs-tudelft/fletcher-alveo/blob/master/examples/sum/hw/alveo/Makefile). That Alveo Makefile should look familiar.
